# Generated by Django 4.2 on 2026-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('realestate', 'Real Estate'), ('shipyard', 'Shipyard')], max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
